name: CI

on: [push, pull_request]

jobs:
  Linux:
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-20.04
          - runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test
      run: |
        make test-in-container
    - name: Verify
      run: |
        dist/Tahoe-LAFS/tahoe --version-and-path
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/Tahoe-LAFS.zip
        name: Tahoe-LAFS-${{ matrix.os.runs-on }}.zip
  macOS:
    strategy:
      matrix:
        os:
          - runs-on: macos-11.0
          - runs-on: macos-10.15
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo rm -rf /Applications/Python*
        brew install openssl readline sqlite3 xz zlib
        git clone --branch 1.2.24 https://github.com/pyenv/pyenv.git ~/.pyenv
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
        echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
        . ~/.zshrc
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        export PYTHON_CONFIGURE_OPTS="--enable-framework"
        env | sort
        pyenv install --skip-existing 2.7.18
        pyenv rehash
        pyenv global 2.7.18
        python2 -m pip install --upgrade setuptools pip virtualenv
    - name: Test
      run: |
        source ~/.zshrc
        make test
    - name: Make (1)
      run: |
        source ~/.zshrc
        make all
    - name: Make (2)
      run: |
        source ~/.zshrc
        make clean all
    - name: Verify
      run: |
        dist/Tahoe-LAFS/tahoe --version-and-path
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/Tahoe-LAFS.zip
        name: Tahoe-LAFS-${{ matrix.os.runs-on }}.zip
  Windows:
    strategy:
      matrix:
        os:
          - runs-on: windows-2019
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        py -2 -m pip install --upgrade virtualenv
    - name: Test
      run: |
        .\make.bat test
    - name: Make (1)
      run: |
        .\make.bat 
    - name: Make (2)
      run: |
        .\make.bat clean
        .\make.bat
    - name: Verify
      run: |
        dist/Tahoe-LAFS/tahoe.exe --version-and-path
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/Tahoe-LAFS.zip
        name: Tahoe-LAFS-${{ matrix.os.runs-on }}.zip 
